# Site settings
title: Sohee Kim - Data AnalArtist
description: A blog about Portfolio
baseurl: "" # the subpath of your site, e.g. /portfolio
url: "http://sosodoit.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: sosodoit
user_description:  I am a Data-AnalArtist
email: rosesh0218@gmail.com
# twitter_username: lorem_ipsum
github_username:  sosodoit
gplus_username:  sosodoit
disqus_username: sosodoit

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
